Update pull-request-check.yml

diff --git a/.github/workflows/pull-request-check.yml b/.github/workflows/pull-request-check.yml
--- a/.github/workflows/pull-request-check.yml
+++ b/.github/workflows/pull-request-check.yml
@@ -1,4 +1,4 @@
-name: Pull Request Check
+name: Pull Request Quality Gate
 
 on:
   pull_request:
@@ -7,45 +7,36 @@ on:
       - synchronize
 
 jobs:
-  analyze_code:
+  quality_gate:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-
-    - name: Run SAST analysis
-      run: echo "Realizando análisis de SAST"
-      id: sast
-
-    - name: Check requirements
+    - name: Check for allow_pull_request.txt
       run: |
         if [ -f "allow_pull_request.txt" ]; then
           echo "Permitiendo Pull Request"
-          echo "allow_pull=true" >> $GITHUB_ENV
+          echo "allow_pull=true" > pull_request_results.txt
         else
           echo "Impidiendo Pull Request"
-          echo "allow_pull=false" >> $GITHUB_ENV
+          echo "allow_pull=false" > pull_request_results.txt
           exit 1
         fi
+      continue-on-error: true
 
-  allow_build:
-    needs: analyze_code
-    runs-on: ubuntu-latest
+    - name: Perform SAST analysis
+      run: echo "Realizando análisis de SAST"
 
-    steps:
-    - name: Check allow_pull variable
+    - name: Check results and allow/deny pull request
       run: |
-        if [ "${{ env.allow_pull }}" = "true" ]; then
-          echo "Permitiendo Pull Request"
+        if [ -f "pull_request_results.txt" ]; then
+          source pull_request_results.txt
+          if [ "$allow_pull" = "true" ]; then
+            echo "Permitiendo Pull Request"
+          else
+            echo "Build fallida. Impidiendo Pull Request"
+            exit 1
+          fi
         else
-          echo "Build fallida. Impidiendo Pull Request"
+          echo "Result file not found. Impidiendo Pull Request"
           exit 1
         fi
-
-    - name: Save allow_pull_request.txt as artifact
-      if: always()
-      uses: actions/upload-artifact@v2
-      with:
-        name: allow_pull_request
-        path: allow_pull_request.txt
